name: NodeJS CI

on: 
  push: 
    branch: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Using NodeJS ${{ matrix.node-version }}
        uses: actions/checkout@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
